<?php
$helper = $this->helper('Chilliapple\DeliveryFrom\Helper\Data');
$price = $helper->getDeliveryFrom();
$formattedPrice = $helper->getFormattedPrice($price);
$currentProduct = $helper->getCurrentProduct();
$poa = $currentProduct->getAttributeText('poa');
?>
<?php if($price > 0 && $poa == NULL): ?>
    <p class="product-delivery"><?php echo __('Delivery from: '); ?><?=  $formattedPrice; ?><span><?= __(' + VAT'); ?></span>
    </p>
<?php endif; ?>